CREATE TABLE `receipts` (
	`id` text PRIMARY KEY NOT NULL,
	`receipt_date` text NOT NULL,
	`arrival_time` text NOT NULL,
	`sese_id` text NOT NULL,
	`shift` text NOT NULL,
	`origin` text NOT NULL,
	`receipt_type` text NOT NULL,
	`warehouse` text NOT NULL,
	`gate` text NOT NULL,
	`supplier` text NOT NULL,
	`carrier` text NOT NULL,
	`invoice_number` text NOT NULL,
	`vehicle_plate` text NOT NULL,
	`driver` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'AGUARDANDO' NOT NULL,
	`has_divergence` integer DEFAULT false NOT NULL,
	`divergence_description` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_by` text NOT NULL,
	`completed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
